### ISSUE TITLE
npm run serve:    error 

### ISSUE THREAD

**Issue by bors9249** [citrucn/OASys-Frontend#2]
This dependency was not found:

* /styles/index.css in ./src/main.js

To install it, you can run: npm install --save /styles/index.css

-------------------------
npm install --save /styles/index.css  这个运行也不对

npm ERR! code ENOLOCAL
npm ERR! Could not install from "..\..\..\..\styles\index.css" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\DevSoftware\npm_node\node\node_cache\_logs\2020-07-09T10_08_20_158Z-debug.log

**Comment by Furinai** [comment]
/styles/index.css只是一个样式文件，不需要通过npm安装，检查一下这个文件是不是缺失了
